[2024-09-24T19:07:03.084Z] info: docker.yaml was copied to the config folder
[2024-09-24T19:07:03.087Z] info: services.yaml was copied to the config folder
[2024-09-24T19:07:03.088Z] info: bookmarks.yaml was copied to the config folder
[2024-09-24T19:07:03.088Z] info: widgets.yaml was copied to the config folder
[2024-09-24T19:07:03.089Z] info: custom.css was copied to the config folder
[2024-09-24T19:07:03.095Z] info: custom.js was copied to the config folder
[2024-09-24T19:07:03.238Z] info: kubernetes.yaml was copied to the config folder
[2024-09-24T20:52:13.922Z] error: <httpProxy> Error calling http://192.168.1.12:8006//api2/json/status/datastore-usage...
[2024-09-24T20:52:13.928Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:96:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:327:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:484:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:92:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
[2024-09-24T20:52:13.929Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://192.168.1.12:8006//api2/json/status/datastore-usage
[2024-09-24T20:52:13.932Z] error: <httpProxy> Error calling http://192.168.1.12:8006//api2/json/nodes/localhost/tasks...
[2024-09-24T20:52:13.933Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:96:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:327:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:484:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:92:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
[2024-09-24T20:52:13.933Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://192.168.1.12:8006//api2/json/nodes/localhost/tasks?errors=true&limit=100&since=1727124733117
[2024-09-24T20:52:13.936Z] error: <httpProxy> Error calling http://192.168.1.12:8006//api2/json/nodes/localhost/status...
[2024-09-24T20:52:13.937Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:96:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:327:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:484:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:92:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
[2024-09-24T20:52:13.937Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://192.168.1.12:8006//api2/json/nodes/localhost/status
[2024-09-24T20:52:26.946Z] error: <httpProxy> Error calling http://192.168.1.12:8006//api2/json/status/datastore-usage...
[2024-09-24T20:52:26.947Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:96:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:327:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:484:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:92:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
[2024-09-24T20:52:26.948Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://192.168.1.12:8006//api2/json/status/datastore-usage
[2024-09-24T20:52:26.950Z] error: <httpProxy> Error calling http://192.168.1.12:8006//api2/json/nodes/localhost/tasks...
[2024-09-24T20:52:26.951Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:96:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:327:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:484:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:92:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
[2024-09-24T20:52:26.952Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://192.168.1.12:8006//api2/json/nodes/localhost/tasks?errors=true&limit=100&since=1727124733117
[2024-09-24T20:52:26.975Z] error: <httpProxy> Error calling http://192.168.1.12:8006//api2/json/nodes/localhost/status...
[2024-09-24T20:52:26.976Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:96:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:327:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:484:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:92:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
[2024-09-24T20:52:26.976Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://192.168.1.12:8006//api2/json/nodes/localhost/status
[2024-09-24T20:53:16.112Z] error: <httpProxy> Error calling http://192.168.1.12:8006//api2/json/status/datastore-usage...
[2024-09-24T20:53:16.113Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:96:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:327:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:484:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:92:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
[2024-09-24T20:53:16.113Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://192.168.1.12:8006//api2/json/status/datastore-usage
[2024-09-24T20:53:16.117Z] error: <httpProxy> Error calling http://192.168.1.12:8006//api2/json/nodes/localhost/tasks...
[2024-09-24T20:53:16.120Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:96:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:327:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:484:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:92:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
[2024-09-24T20:53:16.120Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://192.168.1.12:8006//api2/json/nodes/localhost/tasks?errors=true&limit=100&since=1727124733117
[2024-09-24T20:53:16.123Z] error: <httpProxy> Error calling http://192.168.1.12:8006//api2/json/nodes/localhost/status...
[2024-09-24T20:53:16.124Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:96:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:327:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:484:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:92:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
[2024-09-24T20:53:16.125Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://192.168.1.12:8006//api2/json/nodes/localhost/status
[2024-09-24T20:55:23.080Z] error: <httpProxy> Error calling http://192.168.1.12:8006//api2/json/status/datastore-usage...
[2024-09-24T20:55:23.081Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:96:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:327:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:484:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:92:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
[2024-09-24T20:55:23.081Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://192.168.1.12:8006//api2/json/status/datastore-usage
[2024-09-24T20:55:23.084Z] error: <httpProxy> Error calling http://192.168.1.12:8006//api2/json/nodes/localhost/tasks...
[2024-09-24T20:55:23.085Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:96:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:327:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:484:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:92:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
[2024-09-24T20:55:23.085Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://192.168.1.12:8006//api2/json/nodes/localhost/tasks?errors=true&limit=100&since=1727124733117
[2024-09-24T20:55:23.090Z] error: <httpProxy> Error calling http://192.168.1.12:8006//api2/json/nodes/localhost/status...
[2024-09-24T20:55:23.091Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:96:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:327:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:484:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:92:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
[2024-09-24T20:55:23.091Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://192.168.1.12:8006//api2/json/nodes/localhost/status
[2024-09-24T21:03:39.899Z] error: <httpProxy> Error calling http://192.168.1.12:8006//api2/json/nodes/localhost/tasks...
[2024-09-24T21:03:39.900Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:96:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:327:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:484:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:92:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
[2024-09-24T21:03:39.900Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://192.168.1.12:8006//api2/json/nodes/localhost/tasks?errors=true&limit=100&since=1727124733117
[2024-09-24T21:03:39.908Z] error: <httpProxy> Error calling http://192.168.1.12:8006//api2/json/nodes/localhost/status...
[2024-09-24T21:03:39.909Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:96:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:327:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:484:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:92:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
[2024-09-24T21:03:39.910Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://192.168.1.12:8006//api2/json/nodes/localhost/status
[2024-09-24T21:03:39.920Z] error: <httpProxy> Error calling http://192.168.1.12:8006//api2/json/status/datastore-usage...
[2024-09-24T21:03:39.921Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:96:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:327:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:484:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:92:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
[2024-09-24T21:03:39.921Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://192.168.1.12:8006//api2/json/status/datastore-usage
[2024-09-24T21:08:01.061Z] error: <httpProxy> Error calling http://192.168.1.12:8006//api2/json/status/datastore-usage...
[2024-09-24T21:08:01.066Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:96:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:327:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:484:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:92:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
[2024-09-24T21:08:01.067Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://192.168.1.12:8006//api2/json/status/datastore-usage
[2024-09-24T21:08:01.071Z] error: <httpProxy> Error calling http://192.168.1.12:8006//api2/json/nodes/localhost/status...
[2024-09-24T21:08:01.072Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:96:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:327:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:484:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:92:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
[2024-09-24T21:08:01.073Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://192.168.1.12:8006//api2/json/nodes/localhost/status
[2024-09-24T21:08:01.088Z] error: <httpProxy> Error calling http://192.168.1.12:8006//api2/json/nodes/localhost/tasks...
[2024-09-24T21:08:01.089Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:96:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:327:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:484:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:92:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
[2024-09-24T21:08:01.090Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://192.168.1.12:8006//api2/json/nodes/localhost/tasks?errors=true&limit=100&since=1727125679989
[2024-09-24T21:08:01.897Z] error: <httpProxy> Error calling http://192.168.1.12:8006//api2/json/status/datastore-usage...
[2024-09-24T21:08:01.909Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:96:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:327:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:484:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:92:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
[2024-09-24T21:08:01.909Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://192.168.1.12:8006//api2/json/status/datastore-usage
[2024-09-24T21:08:01.915Z] error: <httpProxy> Error calling http://192.168.1.12:8006//api2/json/nodes/localhost/tasks...
[2024-09-24T21:08:01.916Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:96:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:327:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:484:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:92:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
[2024-09-24T21:08:01.917Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://192.168.1.12:8006//api2/json/nodes/localhost/tasks?errors=true&limit=100&since=1727125679989
[2024-09-24T21:08:01.923Z] error: <httpProxy> Error calling http://192.168.1.12:8006//api2/json/nodes/localhost/status...
[2024-09-24T21:08:01.924Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:96:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:327:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:484:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:92:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
[2024-09-24T21:08:01.924Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://192.168.1.12:8006//api2/json/nodes/localhost/status
[2024-09-24T21:08:20.521Z] error: <httpProxy> Error calling http://192.168.1.12:8006//api2/json/status/datastore-usage...
[2024-09-24T21:08:20.522Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:96:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:327:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:484:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:92:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
[2024-09-24T21:08:20.523Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://192.168.1.12:8006//api2/json/status/datastore-usage
[2024-09-24T21:08:20.526Z] error: <httpProxy> Error calling http://192.168.1.12:8006//api2/json/nodes/localhost/tasks...
[2024-09-24T21:08:20.527Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:96:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:327:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:484:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:92:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
[2024-09-24T21:08:20.527Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://192.168.1.12:8006//api2/json/nodes/localhost/tasks?errors=true&limit=100&since=1727125679989
[2024-09-24T21:08:20.530Z] error: <httpProxy> Error calling http://192.168.1.12:8006//api2/json/nodes/localhost/status...
[2024-09-24T21:08:20.531Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:96:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:327:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:484:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:92:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
[2024-09-24T21:08:20.531Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://192.168.1.12:8006//api2/json/nodes/localhost/status
[2024-09-24T21:08:46.142Z] error: <httpProxy> Error calling http://192.168.1.12:8006//api2/json/status/datastore-usage...
[2024-09-24T21:08:46.143Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:96:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:327:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:484:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:92:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
[2024-09-24T21:08:46.144Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://192.168.1.12:8006//api2/json/status/datastore-usage
[2024-09-24T21:08:46.147Z] error: <httpProxy> Error calling http://192.168.1.12:8006//api2/json/nodes/localhost/tasks...
[2024-09-24T21:08:46.148Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:96:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:327:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:484:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:92:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
[2024-09-24T21:08:46.148Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://192.168.1.12:8006//api2/json/nodes/localhost/tasks?errors=true&limit=100&since=1727125679989
[2024-09-24T21:08:46.152Z] error: <httpProxy> Error calling http://192.168.1.12:8006//api2/json/nodes/localhost/status...
[2024-09-24T21:08:46.153Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:96:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:327:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:484:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:92:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
[2024-09-24T21:08:46.153Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://192.168.1.12:8006//api2/json/nodes/localhost/status
[2024-09-24T21:09:01.851Z] error: <httpProxy> Error calling http://192.168.1.12:8006//api2/json/nodes/localhost/tasks...
[2024-09-24T21:09:01.852Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:96:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:327:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:484:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:92:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
[2024-09-24T21:09:01.853Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://192.168.1.12:8006//api2/json/nodes/localhost/tasks?errors=true&limit=100&since=1727125679989
[2024-09-24T21:09:01.859Z] error: <httpProxy> Error calling http://192.168.1.12:8006//api2/json/nodes/localhost/status...
[2024-09-24T21:09:01.860Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:96:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:327:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:484:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:92:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
[2024-09-24T21:09:01.860Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://192.168.1.12:8006//api2/json/nodes/localhost/status
[2024-09-24T21:09:01.879Z] error: <httpProxy> Error calling http://192.168.1.12:8006//api2/json/status/datastore-usage...
[2024-09-24T21:09:01.880Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:96:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:327:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:484:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:92:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
[2024-09-24T21:09:01.880Z] error: <credentialedProxyHandler> HTTP Error 500 calling http://192.168.1.12:8006//api2/json/status/datastore-usage
[2024-09-24T21:12:20.966Z] error: <credentialedProxyHandler> HTTP Error 501 calling https://192.168.1.12:8006//api2/json/status/datastore-usage
[2024-09-24T21:12:20.970Z] error: <credentialedProxyHandler> HTTP Error 501 calling https://192.168.1.12:8006//api2/json/nodes/localhost/status
[2024-09-24T21:12:20.971Z] error: <credentialedProxyHandler> HTTP Error 501 calling https://192.168.1.12:8006//api2/json/nodes/localhost/tasks?errors=true&limit=100&since=1727125679989
[2024-09-24T21:12:21.428Z] error: <credentialedProxyHandler> HTTP Error 501 calling https://192.168.1.12:8006//api2/json/status/datastore-usage
[2024-09-24T21:12:21.433Z] error: <credentialedProxyHandler> HTTP Error 501 calling https://192.168.1.12:8006//api2/json/nodes/localhost/status
[2024-09-24T21:12:21.434Z] error: <credentialedProxyHandler> HTTP Error 501 calling https://192.168.1.12:8006//api2/json/nodes/localhost/tasks?errors=true&limit=100&since=1727125679989
[2024-09-24T21:12:26.461Z] error: <credentialedProxyHandler> HTTP Error 501 calling https://192.168.1.12:8006//api2/json/nodes/localhost/tasks?errors=true&limit=100&since=1727125679989
[2024-09-24T21:12:30.821Z] error: <credentialedProxyHandler> HTTP Error 501 calling https://192.168.1.12:8006//api2/json/nodes/localhost/status
[2024-09-24T21:12:30.822Z] error: <credentialedProxyHandler> HTTP Error 501 calling https://192.168.1.12:8006//api2/json/nodes/localhost/tasks?errors=true&limit=100&since=1727125679989
[2024-09-24T21:12:30.828Z] error: <credentialedProxyHandler> HTTP Error 501 calling https://192.168.1.12:8006//api2/json/status/datastore-usage
[2024-09-24T21:12:36.492Z] error: <credentialedProxyHandler> HTTP Error 501 calling https://192.168.1.12:8006//api2/json/nodes/localhost/tasks?errors=true&limit=100&since=1727125679989
[2024-09-24T21:12:41.523Z] error: <credentialedProxyHandler> HTTP Error 501 calling https://192.168.1.12:8006//api2/json/nodes/localhost/status
[2024-09-24T21:12:41.537Z] error: <credentialedProxyHandler> HTTP Error 501 calling https://192.168.1.12:8006//api2/json/status/datastore-usage
[2024-09-24T21:13:27.345Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/status/datastore-usage
[2024-09-24T21:13:27.347Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/nodes/localhost/tasks?errors=true&limit=100&since=1727125679989
[2024-09-24T21:13:27.347Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/nodes/localhost/status
[2024-09-24T21:13:27.650Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/status/datastore-usage
[2024-09-24T21:13:27.652Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/nodes/localhost/status
[2024-09-24T21:13:27.653Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/nodes/localhost/tasks?errors=true&limit=100&since=1727125679989
[2024-09-24T21:13:35.817Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/status/datastore-usage
[2024-09-24T21:13:35.822Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/nodes/localhost/status
[2024-09-24T21:13:35.823Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/nodes/localhost/tasks?errors=true&limit=100&since=1727125679989
[2024-09-24T21:13:44.516Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/status/datastore-usage
[2024-09-24T21:13:44.517Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/nodes/localhost/tasks?errors=true&limit=100&since=1727125679989
[2024-09-24T21:13:44.527Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/nodes/localhost/status
[2024-09-24T21:13:44.786Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/status/datastore-usage
[2024-09-24T21:13:44.788Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/nodes/localhost/tasks?errors=true&limit=100&since=1727125679989
[2024-09-24T21:13:44.790Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/nodes/localhost/status
[2024-09-24T21:14:01.109Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/status/datastore-usage
[2024-09-24T21:14:01.110Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/nodes/localhost/status
[2024-09-24T21:14:01.112Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/nodes/localhost/tasks?errors=true&limit=100&since=1727125679989
[2024-09-24T21:14:09.133Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/status/datastore-usage
[2024-09-24T21:14:09.137Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/nodes/localhost/status
[2024-09-24T21:14:09.147Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/nodes/localhost/tasks?errors=true&limit=100&since=1727125679989
[2024-09-24T21:14:22.162Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/status/datastore-usage
[2024-09-24T21:14:29.253Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/nodes/localhost/tasks?errors=true&limit=100&since=1727125679989
[2024-09-24T21:14:29.254Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/status/datastore-usage
[2024-09-24T21:14:29.255Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/nodes/localhost/status
[2024-09-24T21:14:32.491Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/nodes/localhost/status
[2024-09-24T21:14:32.493Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/nodes/localhost/tasks?errors=true&limit=100&since=1727125679989
[2024-09-24T21:15:05.187Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/status/datastore-usage
[2024-09-24T21:18:12.755Z] error: <servicesProxy> TypeError: Cannot read properties of undefined (reading 'method')
    at handler (/app/.next/server/pages/api/services/proxy.js:438:21)
    at async Object.apiResolver (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/api-utils/node.js:366:9)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:481:9)
    at async Object.fn (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:741:37)
    at async Router.execute (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/router.js:252:36)
    at async NextNodeServer.run (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:365:29)
    at async NextNodeServer.handleRequest (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:303:20)
    at async Server.<anonymous> (/app/server.js:19:5)
[2024-09-24T21:18:12.756Z] error: <servicesProxy> TypeError: Cannot read properties of undefined (reading 'method')
    at handler (/app/.next/server/pages/api/services/proxy.js:438:21)
    at async Object.apiResolver (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/api-utils/node.js:366:9)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:481:9)
    at async Object.fn (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:741:37)
    at async Router.execute (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/router.js:252:36)
    at async NextNodeServer.run (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:365:29)
    at async NextNodeServer.handleRequest (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:303:20)
    at async Server.<anonymous> (/app/server.js:19:5)
[2024-09-24T21:18:12.757Z] error: <servicesProxy> TypeError: Cannot read properties of undefined (reading 'method')
    at handler (/app/.next/server/pages/api/services/proxy.js:438:21)
    at async Object.apiResolver (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/api-utils/node.js:366:9)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:481:9)
    at async Object.fn (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:741:37)
    at async Router.execute (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/router.js:252:36)
    at async NextNodeServer.run (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:365:29)
    at async NextNodeServer.handleRequest (/app/node_modules/.pnpm/next@12.3.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:303:20)
    at async Server.<anonymous> (/app/server.js:19:5)
[2024-09-24T21:18:16.049Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-24T21:18:16.696Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-24T21:18:24.718Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-24T21:18:28.546Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-24T21:18:41.653Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-24T21:21:53.179Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-24T21:21:53.628Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-24T21:22:06.978Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-24T21:22:21.170Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-24T21:22:34.335Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-24T21:23:18.849Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-24T21:25:24.124Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-24T21:25:29.270Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-24T21:26:46.554Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-24T21:27:38.342Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-24T21:27:39.935Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-24T21:27:48.064Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-24T21:28:17.226Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-24T21:29:53.500Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-24T21:29:53.922Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-24T21:29:59.520Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-24T21:30:07.573Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-24T21:30:34.566Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-24T21:30:47.598Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-24T21:31:00.630Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:31:46.048Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:31:46.278Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:31:52.946Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:31:59.300Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:32:22.334Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:32:45.854Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:32:56.085Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:36:01.776Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:36:02.206Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:36:15.228Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:36:28.263Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:37:06.450Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:38:01.659Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:38:01.938Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:38:36.484Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:38:37.153Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:38:50.192Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:41:40.565Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:41:41.071Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:41:49.096Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:42:24.360Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:42:24.713Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:42:32.746Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:47:43.653Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:47:43.993Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:47:50.702Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:47:57.018Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:48:03.958Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:48:15.051Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:48:32.980Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:48:33.307Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:48:38.989Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:48:52.585Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:54:16.781Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:54:17.263Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:54:24.091Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:54:30.286Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:54:43.319Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:55:16.027Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:55:27.342Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:56:53.716Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:56:54.159Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:57:00.990Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T18:57:07.231Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T19:00:39.735Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T19:00:40.105Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T19:00:45.845Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T19:00:53.170Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T19:01:24.988Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T19:01:25.390Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T19:01:38.412Z] error: <credentialedProxyHandler> HTTP Error 401 calling https://192.168.1.12:8006/api2/json/cluster/resources
[2024-09-26T20:01:25.148Z] error: <httpProxy> Error calling http://192.168.1.1//api/diagnostics/traffic/interface...
[2024-09-26T20:01:25.154Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:96:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:327:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:484:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:92:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
[2024-09-26T20:01:25.158Z] error: <httpProxy> Error calling http://192.168.1.1//api/diagnostics/activity/getActivity...
[2024-09-26T20:01:25.159Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:96:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:327:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:484:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:92:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
[2024-09-26T20:01:25.476Z] error: <httpProxy> Error calling http://192.168.1.1//api/diagnostics/activity/getActivity...
[2024-09-26T20:01:25.477Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:96:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:327:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:484:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:92:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
[2024-09-26T20:01:25.486Z] error: <httpProxy> Error calling http://192.168.1.1//api/diagnostics/traffic/interface...
[2024-09-26T20:01:25.488Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:96:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:327:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:484:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:92:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
[2024-09-26T20:01:35.596Z] error: <httpProxy> Error calling http://192.168.1.1//api/diagnostics/activity/getActivity...
[2024-09-26T20:01:35.598Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:96:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:327:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:484:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:92:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
[2024-09-26T20:01:35.601Z] error: <httpProxy> Error calling http://192.168.1.1//api/diagnostics/traffic/interface...
[2024-09-26T20:01:35.602Z] error: <httpProxy> [
  500,
  Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"
      at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:96:17)
      at Object.onceWrapper (node:events:632:26)
      ... 2 lines matching cause stack trace ...
      at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
      at Socket.socketOnData (node:_http_client:541:22)
      at Socket.emit (node:events:517:28)
      at addChunk (node:internal/streams/readable:368:12)
      at readableAddChunk (node:internal/streams/readable:341:9)
      at Readable.push (node:internal/streams/readable:278:10) {
    cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
        at new NodeError (node:internal/errors:405:5)
        at new ClientRequest (node:_http_client:188:11)
        at Object.request (node:https:366:10)
        at RedirectableRequest._performRequest (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:327:24)
        at RedirectableRequest._processResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:484:8)
        at RedirectableRequest._onNativeResponse (/app/node_modules/.pnpm/follow-redirects@1.15.8/node_modules/follow-redirects/index.js:92:12)
        at Object.onceWrapper (node:events:632:26)
        at ClientRequest.emit (node:events:517:28)
        at HTTPParser.parserOnIncomingClient (node:_http_client:700:27)
        at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17) {
      code: 'ERR_INVALID_PROTOCOL'
    },
    code: 'ERR_FR_REDIRECTION_FAILURE'
  }
]
